
services:
  react-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PORT: ${PORT}
    container_name: notelist-react-app-dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped
